### ISSUE TITLE
Build error on   __builtin_astype(textureObject->sampler, sampler_t),

### ISSUE THREAD

**Issue by pengtu** [jz10/anl-gt-gpu#32]
I am getting the following build error:

make
[  1%] Building y1F.bc
[  2%] Building mathlib.bc
/home/peng_20/hip/anl-gt-gpu/hipcl/lib/bitcode/mathlib.cl:767:5: error: 
      internal error: could not emit constant value "abstractly"
    __builtin_astype(textureObject->sampler, sampler_t),
    ^
1 error generated.
make[2]: *** [lib/bitcode/CMakeFiles/kernellib_bc.dir/build.make:170: lib/bitcode/BC/mathlib.bc] Error 1
make[1]: *** [CMakeFiles/Makefile2:823: lib/bitcode/CMakeFiles/kernellib_bc.dir/all] Error 2

My cmake configuration is:

cmake -DCMAKE_CXX_COMPILER=/home/peng_20/hip/llvm/build_hipcl/bin/clang++ -DCMAKE_C_COMPILER=/home/peng_20/hip/llvm/build_hipcl/bin/clang -DLevel_0_INCLUDE_DIR=/home/peng/sycl_workspace/llvm/build_cuda11/include/sycl/level_zero -DLevel_0_LIBRARIES=/home/peng/sycl_workspace/llvm/build_cuda11/lib/libze_loader.so -DOpenCL_INCLUDE_DIR=/usr/include/CL -DOpenCL_LIBRARY=/home/peng/sycl_workspace/llvm/build_cuda11/lib/libOpenCL.so ..
-- The C compiler identification is Clang 8.0.1
-- The CXX compiler identification is Clang 8.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/peng_20/hip/llvm/build_hipcl/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/peng_20/hip/llvm/build_hipcl/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HipCL will be installed to: /opt/hiplz
-- Using Clang: /home/peng_20/hip/llvm/build_hipcl/bin/clang++
-- Using llvm-link: /home/peng_20/hip/llvm/build_hipcl/bin/llvm-link
-- Using llvm-spirv: /home/peng_20/hip/llvm/build_hipcl/bin/llvm-spirv
-- Using llvm-config: /home/peng_20/hip/llvm/build_hipcl/bin/llvm-config
-- CMake build type not set, setting to RelWithDebInfo
-- CMake build type: RelWithDebInfo
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Found OpenCL: /home/peng/sycl_workspace/llvm/build_cuda11/lib/libOpenCL.so (Required is at least version "2.0") 
-- LLVM CMake directory: /home/peng_20/hip/llvm/build_hipcl/lib/cmake/llvm
-- hiplz private compile options: -Wno-unused-parameter
-- hiplz private include directories: $<INSTALL_INTERFACE:/opt/hiplz/include>;$<BUILD_INTERFACE:/home/peng_20/hip/anl-gt-gpu/hipcl/include>;/home/peng_20/hip/anl-gt-gpu/hipcl;/home/peng_20/hip/anl-gt-gpu/hipcl/include;/home/peng/sycl_workspace/llvm/build_cuda11/include/sycl/level_zero
-- hiplz public compile options: -x;hip;$<INSTALL_INTERFACE:--hip-device-lib-path=/opt/hiplz/share>;$<BUILD_INTERFACE:--hip-device-lib-path=/home/peng_20/hip/anl-gt-gpu/hipcl/build>;--hip-device-lib=kernellib.bc;$<INSTALL_INTERFACE:--hip-llvm-pass-path=/opt/hiplz/lib/llvm>;$<BUILD_INTERFACE:--hip-llvm-pass-path=/home/peng_20/hip/anl-gt-gpu/hipcl/build/llvm_passes>
-- hiplz public include directories: $<INSTALL_INTERFACE:/opt/hiplz/include>;$<BUILD_INTERFACE:/home/peng_20/hip/anl-gt-gpu/hipcl/include>
-- HIPLZ_CXX_OPTIONS: -x hip $<1:--hip-device-lib-path=/opt/hiplz/share> $<0:--hip-device-lib-path=/home/peng_20/hip/anl-gt-gpu/hipcl/build> --hip-device-lib=kernellib.bc $<1:--hip-llvm-pass-path=/opt/hiplz/lib/llvm> $<0:--hip-llvm-pass-path=/home/peng_20/hip/anl-gt-gpu/hipcl/build/llvm_passes> $<1:-I/opt/hiplz/include> $<0:/home/peng_20/hip/anl-gt-gpu/hipcl/include>
-- Configuring done
-- Generating done
-- Build files have been written to: /home/peng_20/hip/anl-gt-gpu/hipcl/build

Am I missing something in my settings?

Thanks,
Peng.

**Comment by pengtu** [comment]
Here is another build error message:

[ 35%] Building CXX object llvm_passes/CMakeFiles/LLVMHipTexture.dir/HipTexture.cpp.o
In file included from /home/peng_20/hip/anl-gt-gpu/hipcl/llvm_passes/HipTexture.cpp:27:
/home/peng_20/hip/anl-gt-gpu/hipcl/llvm_passes/HipTexture.h:494:42: error: use
      of undeclared identifier 'CloneFunctionChangeType'
      CloneFunctionInto(NewF, origF, VV, CloneFunctionChangeType::Global...
                                         ^
1 error generated.
make[2]: *** [llvm_passes/CMakeFiles/LLVMHipTexture.dir/build.make:76: llvm_passes/CMakeFiles/LLVMHipTexture.dir/HipTexture.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:901: llvm_passes/CMakeFiles/LLVMHipTexture.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

Looking at a similar call to CloneFunctionInto in HipDynMem.cpp:  

#if LLVM_VERSION_MAJOR > 11
    CloneFunctionInto(NewF, F, VV, CloneFunctionChangeType::GlobalChanges, RI);
#else
    CloneFunctionInto(NewF, F, VV, true, RI);
#endif

Here is another place that won't compile with clang-8.

**Comment by Kerilk** [comment]
@pengtu Sorry I couldn't get there sooner. Indeed we use a more recent version of Clang, plus a slightly modified LLVM-SPIRV-Translator that can be found on https://github.com/parmance and that should be available.

**Comment by pengtu** [comment]
@Kerilk Thank you! I am closing this one now.
